INSERT IGNORE INTO site_content (page_section, content) VALUES
('page_title','Reliable Mining, Industrial & HSE Solutions'),
('meta_description','Brethren Mining Solution Limited – Your trusted partner in mining, industrial engineering, construction, and HSE solutions across Tanzania.'),
('og_description','Reliable mining, industrial & HSE solutions in Tanzania.'),
('nav_cta_label','Get Quote'),('nav_cta_url','#contact'),
('vmv_heading','Our Vision, Mission & Values'),
('vmv_subtitle','Guided by a clear purpose and strong principles that define who we are and how we operate.'),
('why_heading','Why Choose Us'),
('why_subtitle','What sets us apart in the mining and industrial solutions landscape.'),
('contact_info_heading','Contact Information'),
('form_heading','Send Us a Message'),
('form_label_name','Name *'),('form_label_email','Email *'),('form_label_phone','Phone'),('form_label_company','Company'),('form_label_message','Message *'),
('form_placeholder_name','Your full name'),('form_placeholder_email','your@email.com'),('form_placeholder_phone','+255 XXX XXX XXX'),('form_placeholder_company','Your company name'),('form_placeholder_message','Tell us about your project...'),
('form_error_name','Please enter your name.'),('form_error_email','Please enter a valid email.'),('form_error_phone','Please enter a valid phone number.'),('form_error_message','Please enter at least 10 characters.'),
('form_submit_text','Send Message'),
('form_success_text','Thank you! Your message has been sent successfully. We will get back to you shortly.'),
('form_error_generic','Something went wrong. Please try again.'),
('form_error_network','Network error. Please try again.'),
('form_sending_text','Sending...'),
('read_more_text','Read More'),
('about_img_alt','About BMSL'),
('legal_cert_alt','Certificate of Incorporation'),
('legal_tra_alt','TRA Registration'),
('footer_heading_quicklinks','Quick Links'),
('footer_heading_services','Services'),
('footer_heading_contact','Contact'),
('back_to_top_label','Back to top');
